/* ============================================================
   표지 그림 만들기

       npm run hero              전부 다시 만듭니다
       npm run hero -- 슬러그     그 글 것만

   글마다 맨 위에 오는 표지 그림(히어로)을 assets/diagrams/ 에 네 벌로 찍어냅니다.

       hero-<슬러그>.svg          900x300  넓은 화면
       hero-<슬러그>-narrow.svg   360x320  폰(560px 이하)
       hero-<슬러그>-en.svg
       hero-<슬러그>-en-narrow.svg

   본문에서는 머리말 바로 밑에 한 줄 적습니다. scripts/diagram.js 가 펴 넣습니다.

       {{svg: hero-<슬러그>}}          (영문판은 {{svg: hero-<슬러그>-en}})

   파일이 셋으로 갈려 있습니다.

       hero-kit.js     테두리 · 그러데이션 · 점 무늬 · 칩 · 캡션. 글마다 같은 것
       hero-specs.js   가운데 그림과 문구. 글마다 다른 것
       make-hero.js    이 파일. 위 둘을 합쳐 파일로 떨굽니다

   왜 손으로 안 그리고 찍어내는가.
   글 한 편에 네 벌이라 여덟 편이면 서른두 개입니다. 손으로 그리면 테두리 두께나 점 무늬
   간격 같은 것이 파일마다 조금씩 어긋나고, 그러면 글마다 표지가 다른 사이트처럼 보입니다.
   더 큰 이유는 고칠 때입니다. 색 하나 바꾸려고 서른두 파일을 여는 일이 생기면 안 바꾸게 됩니다.

   그림은 커밋합니다. 빌드 때 만들지 않습니다.
   빌드에서 만들면 그림이 바뀐 걸 사람이 못 보고 지나갑니다. 파일로 두면 diff 에 걸립니다.
   ============================================================ */
const fs = require("fs");
const path = require("path");
const { chrome, WIDE, NARROW, OUT } = require("./hero-kit.js");
const { SPECS } = require("./hero-specs.js");

/* 그림 파일 위에 남기는 말. 열어본 사람에게 이게 손으로 고칠 파일이 아니라는 걸 알려줍니다. */
function note(spec, lang, box) {
  const wide = box.mode === "w";
  if (lang === "en") {
    return `<!-- Generated by scripts/make-hero.js. Do not edit this file by hand;
       the next run overwrites it. Change scripts/hero-specs.js (entry "${spec.key}") instead.
       ${wide ? "Wide version." : "Vertical version for phones."} Its pair is the ${wide ? "narrow" : "wide"} file, and both come from the same entry.
       Elements marked data-standalone are only for viewing this file on its own; they are
       stripped when the SVG is inlined so colors follow the site variables and the theme toggle works. -->`;
  }
  return `<!-- scripts/make-hero.js 가 만든 파일입니다. 손으로 고치지 마세요. 다음 실행 때 덮어씁니다.
       고칠 곳은 scripts/hero-specs.js 의 "${spec.key}" 항목입니다.
       ${wide ? "넓은 화면용입니다." : "폰용 세로 배치입니다. 가로를 그대로 줄이면 아래 한 줄이 5px 로 찍힙니다."}
       짝은 ${wide ? "narrow" : "가로"} 파일이고 둘 다 같은 항목에서 나옵니다.
       data-standalone 이 붙은 것은 이 파일을 그냥 열어봤을 때만 씁니다. 펴 넣을 때 빠지고,
       색은 사이트의 --card, --accent 를 그대로 받아 테마 토글을 따라옵니다. -->`;
}

function build(only) {
  const targets = only ? SPECS.filter((s) => s.slug === only || s.key === only) : SPECS;
  if (!targets.length) {
    console.error(`  [없음] "${only}" 에 해당하는 항목이 scripts/hero-specs.js 에 없습니다.`);
    console.error(`  있는 것: ${SPECS.map((s) => s.slug).join(", ")}`);
    process.exit(1);
  }
  fs.mkdirSync(OUT, { recursive: true });
  let count = 0;
  for (const spec of targets) {
    for (const lang of ["ko", "en"]) {
      for (const box of [WIDE, NARROW]) {
        spec.note = { [lang]: note(spec, lang, box) };
        const name = `hero-${spec.slug}${lang === "en" ? "-en" : ""}${box.mode === "n" ? "-narrow" : ""}.svg`;
        fs.writeFileSync(path.join(OUT, name), chrome(spec, box, lang), "utf8");
        count++;
      }
    }
    console.log(`  ${spec.slug}`);
  }
  console.log(`\n표지 ${targets.length}편, 파일 ${count}개를 만들었습니다. assets/diagrams/`);
  console.log(`본문 머리말 밑에 {{svg: hero-<슬러그>}} 한 줄이 있어야 나옵니다.`);
}

build(process.argv[2]);
